server:
  port: 8081  # auth-service будет на другом порту

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081  # временный issuer

jwt:
  secret: "supersecretkey123456"  # лучше хранить в vault или environment
  expiration-ms: 3600000           # 1 час
